#!/usr/bin/env node
const exec    = require('shelljs').exec;
const fs      = require('fs');
const file    = require('path').join(__dirname, '../package.json');
const origin  = fs.readFileSync(file, 'utf-8');
const json    = require('../package');
const version = json.version;

/**
 * Nodejitsu does not support multiply environments
 * and works only with one package.json
 * Current package.json uses production.
 *
 * This script does hack:
 * - replace `subdomain` and `domains` values in package.json,
 * - do deploy
 * - rewrite package.json back
 */

json.name = 'porchetta-staging';
json.subdomain = 'porchetta-staging';
json.domains = ['porchetta.activecell.net'];

fs.writeFileSync(file, JSON.stringify(json, null, '  '), 'utf-8');
exec('jitsu deploy -r ' + version, function() {
  fs.writeFileSync(file, origin);
});
