#!/usr/bin/env node
const exec    = require('shelljs').exec;
const version = require('../package').version;

// `-r` helps prevent ugly rewrite of package.json.
exec('jitsu deploy -r ' + version, { async: true });
